### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dinhngtu** [dinhngtu/vm_unattend#1]
- [ ] Use a full Powershell script for the final specialization/OOBE
- [ ] Detect/customize the location of the specializing Autounattend.xml is not present
- [ ] Don't restart if Autounattend.xml is not present (using exit code)
- [ ] Copy stage2 and PS script onto template using stage1
- [ ] Automatically call Sysprep /generalize in stage1
